import type { LibraryResource } from "@/types";

// TODO: populate from roadmap completions — replace this static list by
// aggregating action_item.resources from the user's roadmaps, deduping by
// URL or normalized name, ranking by mention frequency, and tagging with
// skill areas derived from skills_needed and milestone focus_areas.

export const PLACEHOLDER_RESOURCES: LibraryResource[] = [
  {
    id: "placeholder-1",
    name: "MIT OpenCourseWare — Introduction to Algorithms",
    url: "https://ocw.mit.edu",
    cost: "Free",
    type: "free",
    skillArea: "Technical Skills",
    format: "course",
    mentionCount: 12,
    sourceAspiration: "Get into MIT EECS Master's",
  },
  {
    id: "placeholder-2",
    name: "LeetCode Premium",
    url: "https://leetcode.com",
    cost: "$35/mo",
    type: "paid",
    skillArea: "Technical Skills",
    format: "tool",
    mentionCount: 9,
    sourceAspiration: "Software engineering pivot",
  },
  {
    id: "placeholder-3",
    name: "Cracking the Coding Interview",
    url: null,
    cost: "$40",
    type: "paid",
    skillArea: "Interview Prep",
    format: "book",
    mentionCount: 7,
    sourceAspiration: "Software engineering pivot",
  },
  {
    id: "placeholder-4",
    name: "Google Data Analytics Certificate",
    url: "https://www.coursera.org",
    cost: "$49/mo",
    type: "paid",
    skillArea: "Data Analysis",
    format: "certification",
    mentionCount: 5,
    sourceAspiration: "Transition to analytics",
  },
  {
    id: "placeholder-5",
    name: "Khan Academy — Statistics",
    url: "https://www.khanacademy.org",
    cost: "Free",
    type: "free",
    skillArea: "Academic Credentials",
    format: "course",
    mentionCount: 4,
    sourceAspiration: "Transition to analytics",
  },
  {
    id: "placeholder-6",
    name: "How to Write a Research Statement",
    url: null,
    cost: "Free",
    type: "free",
    skillArea: "Academic Writing",
    format: "article",
    mentionCount: 3,
    sourceAspiration: "PhD applications",
  },
  {
    id: "placeholder-7",
    name: "System Design Primer",
    url: "https://github.com/donnemartin/system-design-primer",
    cost: "Free",
    type: "free",
    skillArea: "System Design",
    format: "article",
    mentionCount: 6,
    sourceAspiration: "Senior engineer track",
  },
  {
    id: "placeholder-8",
    name: "NeetCode YouTube — Blind 75",
    url: "https://www.youtube.com",
    cost: "Free",
    type: "free",
    skillArea: "Technical Skills",
    format: "video",
    mentionCount: 8,
    sourceAspiration: "Software engineering pivot",
  },
];
